In [1]:
import pandas as pd
import numpy as np

In [2]:
cleaned_data_full_path = 'D:\\Bridge_Data\\CSV\\Cleaned_Full_Data.csv'
revis_path = 'D:\\Bridge_Data\\Revised_Structure_Type_Col.csv'

In [3]:
full_df = pd.read_csv(cleaned_data_full_path,dtype=str)

In [4]:
pd.set_option('display.max_columns', None)
full_df

,STATE_CODE_001,STRUCTURE_NUMBER_008,DIRECTION_005E,COUNTY_CODE_003,FEATURES_DESC_006A,LOCATION_009,MIN_VERT_CLR_010,KILOPOINT_011,LAT_016,LONG_017,DETOUR_KILOS_019,TOLL_020,MAINTENANCE_021,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,TRAFFIC_LANES_ON_028A,TRAFFIC_LANES_UND_028B,ADT_029,YEAR_ADT_030,DESIGN_LOAD_031,APPR_WIDTH_MT_032,DEGREES_SKEW_034,STRUCTURE_FLARED_035,OPEN_CLOSED_POSTED_041,SERVICE_ON_042A,SERVICE_UND_042B,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,APPR_KIND_044A,APPR_TYPE_044B,MAIN_UNIT_SPANS_045,APPR_SPANS_046,MAX_SPAN_LEN_MT_048,STRUCTURE_LEN_MT_049,ROADWAY_WIDTH_MT_051,DECK_WIDTH_MT_052,OPR_RATING_METH_063,OPERATING_RATING_064,INV_RATING_METH_065,INVENTORY_RATING_066,WORK_PROPOSED_075A,WORK_DONE_BY_075B,IMP_LEN_MT_076,DATE_OF_INSPECT_090,INSPECT_FREQ_MONTHS_091,FRACTURE_092A,UNDWATER_LOOK_SEE_092B,SPEC_INSPECT_092C,FRACTURE_LAST_DATE_093A,UNDWATER_LAST_DATE_093B,SPEC_LAST_DATE_093C,BRIDGE_IMP_COST_094,ROADWAY_IMP_COST_095,TOTAL_IMP_COST_096,YEAR_OF_IMP_097,TRAFFIC_DIRECTION_102,TEMP_STRUCTURE_103,YEAR_RECONSTRUCTED_106,DECK_STRUCTURE_TYPE_107,SURFACE_TYPE_108A,MEMBRANE_TYPE_108B,DECK_PROTECTION_108C,PERCENT_ADT_TRUCK_109,PIER_PROTECTION_111,SCOUR_CRITICAL_113,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,SUBMITTED_BY,BRIDGE_CONDITION,DECK_AREA,STATE_CODE,STRUCTURE_NUMBER,DECK_COND_COMBINED,SUPERSTRUCTURE_COND_COMBINED,SUBSTRUCTURE_COND_COMBINED,CHANNEL_COND_COMBINED,CULVERT_COND_COMBINED,STRUCTURAL_EVAL_COMBINED,DECK_GEOMETRY_EVAL_COMBINED,WATERWAY_EVAL_COMBINED,APPR_ROAD_EVAL_COMBINED,SCOUR_CRITICAL_COMBINED,SUFFICIENCY_RATING_COMBINED,BRIDGE_CONDITION_COMBINED
0,VI,78_STX8205,Not Applicable,NaN,'PEARL B. LARESEN GUT','ROUTE 82',99.99,0,17444259,064411014,13,"Non-Toll Bridge, Non-Toll Road",01,Urban: Collector,1985,2,0,400,2019,Other or Unknown,7.9,45,0,"Open, no restriction",1,5,Concrete,NaN,Other,Other,1,0,8.8,9.8,7.4,11.9,NaN,NaN,0,21.8,NaN,NaN,NaN,12-2019,24,NaN,N,NaN,NaN,NaN,NaN,0,0,0,2015,2-way traffic,NaN,NaN,Concrete Cast-in-Place,Bituminous,Unknown,Unknown,NaN,Navigation protection not required,6,480,2029,78,F,116.62,78,78_STX8205,5_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,5_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,5_5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,N_N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,5_5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,F_F
1,VI,78_STX8001,Not Applicable,NaN,'UNNAMED CREEK','NORTHSHORE ROAD',99.99,0,17453161,064455426,11,"Non-Toll Bridge, Non-Toll Road",01,Urban: Collector,1990,2,0,100,2019,Other or Unknown,7,0,0,"Open, no restriction",1,5,Concrete,NaN,Other,Other,3,0,1.8,6.9,7.4,8.8,NaN,NaN,0,21.8,NaN,NaN,NaN,12-2019,24,NaN,N,NaN,NaN,NaN,NaN,0,0,0,2015,2-way traffic,NaN,NaN,Not Applicable,Monolithic Concrete (concurrently placed with ...,None,Unknown,NaN,Navigation protection not required,6,120,2029,78,F,60.72,78,78_STX8001,N_5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,N_N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,N_N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,4_4_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,5_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,5_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,F_F
2,VI,78_STX7520,Not Applicable,NaN,'UNNAMED GUT','2.4 MILES FROM HWY 66',99.99,0,17415797,064452280,8,"Non-Toll Bridge, Non-Toll Road",01,Urban: Collector,2001,2,0,24,2019,Other or Unknown,10.9,0,0,"Open, no restriction",1,5,Concrete,NaN,Other,Other,1,0,13.1,13.1,8.6,0,NaN,NaN,0,21.8,NaN,NaN,NaN,12-2019,24,NaN,N,NaN,NaN,NaN,NaN,0,0,0,2015,2-way traffic,NaN,NaN,Not Applicable,Bituminous,None,None,NaN,Navigation protection not required,6,30,2029,78,G,142.79,78,78_STX7520,N_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,N_N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,N_N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,8_8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,9_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,G_F
3,VI,78_STX73205,Not Applicable,NaN,'UNNAMED GUT','WINDSOR ROAD',99.99,0,17451424,064464580,6,"Non-Toll Bridge, Non-Toll Road",01,Urban: Collector,2006,2,0,300,2019,Other or Unknown,7.3,0,0,"Open, no restriction",1,5,Prestressed concrete,NaN,Other,Other,5,0,21.9,97.1,10.2,12.3,NaN,NaN,0,21.8,NaN,NaN,NaN,12-2019,24,NaN,N,NaN,NaN,NaN,NaN,0,0,0,2015,2-way traffic,NaN,NaN,Concrete Cast-in-Place,Monolithic Concrete (concurrently placed with ...,None,Unknown,NaN,Navigation protection not required,6,360,2029,78,F,1194.33,78,78_STX73205,7_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,N_N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,9_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,F_F
4,VI,78_STX7310,Not Applicable,NaN,'UNNAMED GUT','HIGHWAY 73',99.99,0,17450506,064471605,13,"Non-Toll Bridge, Non-Toll Road",01,Urban: Collector,2006,2,0,120,2019,Other or Unknown,7.3,10,0,"Open, no restriction",1,5,Concrete,NaN,Other,Other,4,0,11.7,42.7,10.9,11.7,NaN,NaN,0,21.8,35,Work to be done by contract,NaN,12-2019,24,NaN,N,NaN,NaN,NaN,NaN,0,0,0,2015,2-way traffic,NaN,NaN,Concrete Cast-in-Place,Monolithic Concrete (concurrently placed with ...,None,None,NaN,Navigation protection not required,6,124,2029,78,F,499.59,78,78_STX7310,6_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,N_N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,F_G
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
618449,AL,01_000001014002450,Not Applicable,Lawrence County,'TENNESSEE RIVER','ON WHEELER DAM',4.52,39.429,34481800,087225400,42,"Non-Toll Bridge, Non-Toll Road",67,Rural: Minor Arterial,1937,2,0,5520,2017,M 18,7.9,0,0,"Open, no restriction",5,5,Steel,NaN,Girder and Floorbeam System,Stringer/Multi-beam or Girder,2,143,53.3,1981.2,6.1,7.8,Load Factor (LF),NaN,1,23.9,31,Work to be done by contract,1981.2,06-2019,24,24 Months,N,NaN,00-20619,NaN,NaN,50000,2000,60000,NaN,2-way traffic,NaN,1962,Concrete Cast-in-Place,None (no additional concrete thickness or wear...,None,None,10,Navigation protection not required,5,9000,2037,67,F,15453.36,01,01_000001014002450,5_5_5_6_6_6_6_6_6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_7_...,5_5_5_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_...,5_5_5_5_5_6_6_6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_7_...,2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_...,8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,5_5_5_9_9_9_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,45.9_49.9_49.9_59_59_59_59_59_59_59_59_59_59_5...,F_F
618450,AL,01_000000883039900,Not Applicable,Franklin County,'LITTLE BEAR CR. DAM SPW','LITTLE BEAR CR DAM',99.99,0,34270600,087581200,16,"Non-Toll Bridge, Non-Toll Road",67,Rural: Minor Collector,1974,2,0,430,2017,MS 18,11.6,99,0,"Open, no restriction",1,9,Prestressed concrete,NaN,Other,Other,5,0,14,65.5,8.7,10.5,Load Factor (LF),NaN,1,26.6,NaN,NaN,NaN,06-2018,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Concrete Cast-in-Place,None (no additional concrete thickness or wear...,None,None,5,NaN,5,600,2037,67,G,687.75,01,01_000000883039900,7_7_7_7_7_7_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,7_7_7_7_7_7_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,7_7_7_7_7_7_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,7_7_7_7_7_7_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_...,6_6_6_6_6_6_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,5_5_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_4_4_4_4_4_...,9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_...,5_5_5_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,90.2_90.2_90.2_90.2_94.8_94.7_94.7_94.7_94.8_9...,G_G
618451,AL,01_0000000000M0022,Not Applicable,Russell County,'UCHEE CREEK','3.4 KM S OF SUNSHINE RD',99.99,0,32174330,-0845837.,18,"Non-Toll Bridge, Non-Toll Road",74,Rural: Local,1942,2,0,375,2017,M 18,10.4,0,0,"Open, no restriction",1,5,Concrete,NaN,Other,Other,3,0,18.3,43,7.3,9,Allowable Stress (AS),NaN,2,37.2,38,Work to be done by contract,52.8,10-2019,24,NaN,Y60,NaN,NaN,0-2017 Months,NaN,1,1,2,2019,2-way traffic,NaN,0,Concrete Cast-in-Place,Monolithic Concrete (concurrently placed with ...,None,None,35,NaN,5,400,2039,74,F,387,01,01_0000000000M0022,5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_7_7_7_7_7_7_7_7_...,5_5_5_5_5_5_5_5_5_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_6_6_6_5_6_6_7_7_7_6_6_6_6_6_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_...,5_5_5_5_5_5_5_5_5_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,5_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_N_N_N_N_N_...,8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_7_7_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_8_8_8_8_8_8_8_8_...,5_5_8_8_8_8_8_8_8_8_8_8_8_8_8_7_7_7_7_7_7_7_7_...,69.5_69.5_69.5_68.5_68.5_68.5_68.5_81.6_81.6_8...,F_F
618452,AL,01_00000000000S703,Not Applicable,Escambia County,'PERDIDO CREEK','ON LYNN MCGEE ROAD',99.99,1.1,31062020,087340890,3,"Non-Toll Bridge, Non-Toll Road",62,Rural: Local,2002,2,0,159,2019,MS 18,6.5,0,0,"Open, no restriction",1,5,Prestressed concrete,NaN,Other,Other,1,0,12.9,13.6,9.1,9.8,Allowable Stress (AS),NaN,2,35.1,NaN,NaN,0,02-2019,24,NaN,N,NaN,NaN,NaN,NaN,0,0,0,2019,2-way traffic,NaN,0,Concrete Precast Panels,Bituminous,None,Unknown,1,NaN,8,200,2039,62,G,133.28,01,01_00000000000S703,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,8_8_8_8_8_8_6_6_6_6_6_6_6_6_6_nan_nan_nan_nan_...,8_8_8_8_8_8_6_6_6_6_6_6_6_6_6_nan_nan_nan_nan_...,100_100_100_100_100_100_100_100_100_100_100_10...,G_G
618453,AL,01_00000000000S702,Not Applicable,Escambia County,'PERDIDO CREEK','11.4KM NW OF ATMORE AL',99.99,1.5,31061094,087341348,3,"Non-Toll Bridge, Non-Toll Road",62,Rural: Local,1999,2,0,50,2019,MS 18,9.7,30,0,"Open, no restriction",1,5,Prestressed concrete,NaN,Other,Other,1,0,14.7,15,9.7,9.7,Allowable Stress (AS),NaN,2,32.7,NaN,NaN,0,02-2019,24,NaN,N,NaN,NaN,NaN,NaN,0,0,0,2019,2-way traffic,NaN,0,Concrete Precast Panels,Bituminous,None,Epoxy Coated Reinforcing,1,NaN,8,59,2039,62,G,145.5,01,01_00000000000S702,8_8_8_8_8_8_7_7_7_8_8_8_8_8_8_8_8_8_nan_nan_na...,8_8_8_8_8_8_7_7_7_8_8_8_8_8_8_8_8_8_nan_nan_na...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_na...,6_6_8_8_8_8_7_7_7_7_7_7_7_7_7_8_8_8_nan_nan_na...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_nan_nan_na...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_na...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_na...,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_8_8_8_nan_nan_na...,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_8_8_8_nan_nan_na...,8_8_8_8_8_8_6_6_6_6_6_6_6_6_6_6_6_6_nan_nan_na...,100_100_100_100_100_100_100_100_100_100_100_10...,G_G

In [5]:
full_df = full_df[(full_df.STATE_CODE_001 != 'VI') & (full_df.STATE_CODE_001 != "AK") & (full_df.STATE_CODE_001 != "HI")& (full_df.STATE_CODE_001 != "GU")& (full_df.STATE_CODE_001 != "PR")]

In [6]:
full_df.drop('STRUCTURE_TYPE_043B',axis=1,inplace=True)

C:\Users\Eaj59\miniconda3\envs\pytorch\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [7]:
full_df = full_df.rename(columns={'STATE_CODE_001': 'STATE_ABBV', 'STATE_CODE': 'STATE_CODE_001'})

In [8]:
full_df = full_df.rename(columns={'STRUCTURE_NUMBER': 'Unique_Bridge_ID'})

In [9]:
full_df.drop('Unique_Bridge_ID',axis=1,inplace=True)

In [10]:
full_df.drop('BRIDGE_CONDITION',axis=1,inplace=True)

In [11]:
full_df.drop('SCOUR_CRITICAL_113',axis=1,inplace=True)

In [12]:
full_df

,STATE_ABBV,STRUCTURE_NUMBER_008,DIRECTION_005E,COUNTY_CODE_003,FEATURES_DESC_006A,LOCATION_009,MIN_VERT_CLR_010,KILOPOINT_011,LAT_016,LONG_017,DETOUR_KILOS_019,TOLL_020,MAINTENANCE_021,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,TRAFFIC_LANES_ON_028A,TRAFFIC_LANES_UND_028B,ADT_029,YEAR_ADT_030,DESIGN_LOAD_031,APPR_WIDTH_MT_032,DEGREES_SKEW_034,STRUCTURE_FLARED_035,OPEN_CLOSED_POSTED_041,SERVICE_ON_042A,SERVICE_UND_042B,STRUCTURE_KIND_043A,APPR_KIND_044A,APPR_TYPE_044B,MAIN_UNIT_SPANS_045,APPR_SPANS_046,MAX_SPAN_LEN_MT_048,STRUCTURE_LEN_MT_049,ROADWAY_WIDTH_MT_051,DECK_WIDTH_MT_052,OPR_RATING_METH_063,OPERATING_RATING_064,INV_RATING_METH_065,INVENTORY_RATING_066,WORK_PROPOSED_075A,WORK_DONE_BY_075B,IMP_LEN_MT_076,DATE_OF_INSPECT_090,INSPECT_FREQ_MONTHS_091,FRACTURE_092A,UNDWATER_LOOK_SEE_092B,SPEC_INSPECT_092C,FRACTURE_LAST_DATE_093A,UNDWATER_LAST_DATE_093B,SPEC_LAST_DATE_093C,BRIDGE_IMP_COST_094,ROADWAY_IMP_COST_095,TOTAL_IMP_COST_096,YEAR_OF_IMP_097,TRAFFIC_DIRECTION_102,TEMP_STRUCTURE_103,YEAR_RECONSTRUCTED_106,DECK_STRUCTURE_TYPE_107,SURFACE_TYPE_108A,MEMBRANE_TYPE_108B,DECK_PROTECTION_108C,PERCENT_ADT_TRUCK_109,PIER_PROTECTION_111,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,SUBMITTED_BY,DECK_AREA,STATE_CODE_001,DECK_COND_COMBINED,SUPERSTRUCTURE_COND_COMBINED,SUBSTRUCTURE_COND_COMBINED,CHANNEL_COND_COMBINED,CULVERT_COND_COMBINED,STRUCTURAL_EVAL_COMBINED,DECK_GEOMETRY_EVAL_COMBINED,WATERWAY_EVAL_COMBINED,APPR_ROAD_EVAL_COMBINED,SCOUR_CRITICAL_COMBINED,SUFFICIENCY_RATING_COMBINED,BRIDGE_CONDITION_COMBINED
2368,WY,56_NEI,Not Applicable,Park County,'Deaver Canal','3 Miles N.W. of Garland',99.99,0.925,44502750,108413910,8,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,2019,2,0,1,2018,HL 93,9.2,0,0,"Open, no restriction",1,5,Concrete continuous,Other,Other,1,0,6.3,6.3,9.1,9.1,NaN,NaN,F,32.4,NaN,NaN,NaN,01-2020,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Not Applicable,Not Applicable (applies only to structures wit...,Not Applicable (applies only to structures wit...,Not Applicable (applies only to structures wit...,0,NaN,1,2038,56,57.33,56,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,G_nan
2369,WY,56_NEH,Not Applicable,Goshen County,'Willy Draw','1.7 Mi N.E. of Lingle',99.99,3.574,42092990,104192310,13,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,2019,2,0,276,2017,MS 22.5,6.3,0,0,Posted for load (may include other restriction...,1,5,Steel,Other,Other,1,0,12,12.2,7.3,7.6,Load Factor (LF),NaN,1,48.4,NaN,NaN,NaN,01-2020,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Corrugated Steel,Monolithic Concrete (concurrently placed with ...,None,None,17,NaN,453,2037,56,92.72,56,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,G_nan
2370,WY,56_NDY,Not Applicable,Fremont County,'Wind River','Dubois',99.99,161.163,43313079,109370096,159,"Non-Toll Bridge, Non-Toll Road",04,Urban: Local,2019,2,0,99,2018,Other or Unknown,7.3,0,0,"Open, no restriction",1,5,Steel,Other,Other,4,0,8.8,32.7,5.3,7.3,Load Factor (LF),NaN,1,59.4,NaN,NaN,NaN,06-2019,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Wood or Timber,Wood or Timber,None,None,0,NaN,116,2038,56,238.71,56,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,3_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,F_nan
2371,WY,56_NDU,Not Applicable,Park County,'S Fork Shoshone River','13 Mi. S.W. Of Cody',99.99,7.723,44243142,109160416,13,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,2018,2,0,276,2017,HL 93,9.1,0,0,"Open, no restriction",1,5,Prestressed concrete,Other,Other,3,0,18.6,48.8,8.4,9.1,NaN,NaN,8,35.6,38,Work to be done by owners forces,76.2,02-2019,24,NaN,N,NaN,NaN,NaN,NaN,27,30,59,2013,2-way traffic,NaN,0,Concrete Precast Panels,None (no additional concrete thickness or wear...,None,None,10,NaN,453,2037,56,444.08,56,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,G_nan
2372,WY,56_NDP,Not Applicable,Converse County,'S. Fork of Walker Creek','20 miles NE of Douglas',99.99,1.036,42572981,105062189,0,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,1950,2,0,3,2018,Other or Unknown,7.3,0,0,"Open, no restriction",1,5,Steel,Other,Other,1,0,0,7.2,7.3,7.3,Load Factor (LF),NaN,1,67.3,NaN,NaN,NaN,09-2018,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Corrugated Steel,Gravel,None,None,0,Navigation protection not required,4,2038,56,52.56,56,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,5_5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,N_N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,5_5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,U_U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,F_F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
618449,AL,01_000001014002450,Not Applicable,Lawrence County,'TENNESSEE RIVER','ON WHEELER DAM',4.52,39.429,34481800,087225400,42,"Non-Toll Bridge, Non-Toll Road",67,Rural: Minor Arterial,1937,2,0,5520,2017,M 18,7.9,0,0,"Open, no restriction",5,5,Steel,Girder and Floorbeam System,Stringer/Multi-beam or Girder,2,143,53.3,1981.2,6.1,7.8,Load Factor (LF),NaN,1,23.9,31,Work to be done by contract,1981.2,06-2019,24,24 Months,N,NaN,00-20619,NaN,NaN,50000,2000,60000,NaN,2-way traffic,NaN,1962,Concrete Cast-in-Place,None (no additional concrete thickness or wear...,None,None,10,Navigation protection not required,9000,2037,67,15453.36,01,5_5_5_6_6_6_6_6_6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_7_...,5_5_5_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_...,5_5_5_5_5_6_6_6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_7_...,2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_...,8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,5_5_5_9_9_9_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,45.9_49.9_49.9_59_59_59_59_59_59_59_59_59_59_5...,F_F
618450,AL,01_000000883039900,Not Applicable,Franklin County,'LITTLE BEAR CR. DAM SPW','LITTLE BEAR CR DAM',99.99,0,34270600,087581200,16,"Non-Toll Bridge, Non-Toll Road",67,Rural: Minor Collector,1974,2,0,430,2017,MS 18,11.6,99,0,"Open, no restriction",1,9,Prestressed concrete,Other,Other,5,0,14,65.5,8.7,10.5,Load Factor (LF),NaN,1,26.6,NaN,NaN,NaN,06-2018,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Concrete Cast-in-Place,None (no additional concrete thickness or wear...,None,None,5,NaN,600,2037,67,687.75,01,7_7_7_7_7_7_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,7_7_7_7_7_7_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,7_7_7_7_7_7_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,7_7_7_7_7_7_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_...,6_6_6_6_6_6_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,5_5_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_4_4_4_4_4_...,9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_...,5_5_5_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,90.2_90.2_90.2_90.2_94.8_94.7_94.7_94.7_94.8_9...,G_G
618451,AL,01_0000000000M0022,Not Applicable,Russell County,'UCHEE CREEK','3.4 KM S OF SUNSHINE RD',99.99,0,32174330,-0845837.,18,"Non-Toll Bridge, Non-Toll Road",74,Rural: Local,1942,2,0,375,2017,M 18,10.4,0,0,"Open, no restriction",1,5,Concrete,Other,Other,3,0,18.3,43,7.3,9,Allowable Stress (AS),NaN,2,37.2,38,Work to be done by contract,52.8,10-2019,24,NaN,Y60,NaN,NaN,0-2017 Months,NaN,1,1,2,2019,2-way traffic,NaN,0,Concrete Cast-in-Place,Monolithic Concrete (concurrently placed with ...,None,None,35,NaN,400,2039,74,387,01,5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_7_7_7_7_7_7_7_7_...,5_5_5_5_5_5_5_5_5_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_6_6_6_5_6_6_7_7_7_6_6_6_6_6_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_...,5_5_5_5_5_5_5_5_5_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,5_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_N_N_N_N_N_...,8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_7_7_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_8_8_8_8_8_8_8_8_...,5_5_8_8_8_8_8_8_8_8_8_8_8_8_8_7_7_7_7_7_7_7_7_...,69.5_69.5_69.5_68.5_68.5_68.5_68.5_81.6_81.6_8...,F_F
618452,AL,01_00000000000S703,Not Applicable,Escambia County,'PERDIDO CREEK','ON LYNN MCGEE ROAD',99.99,1.1,31062020,087340890,3,"Non-Toll Bridge, Non-Toll Road",62,Rural: Local,2002,2,0,159,2019,MS 18,6.5,0,0,"Open, no restriction",1,5,Prestressed concrete,Other,Other,1,0,12.9,13.6,9.1,9.8,Allowable Stress (AS),NaN,2,35.1,NaN,NaN,0,02-2019,24,NaN,N,NaN,NaN,NaN,NaN,0,0,0,2019,2-way traffic,NaN,0,Concrete Precast Panels,Bituminous,None,Unknown,1,NaN,200,2039,62,133.28,01,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,8_8_8_8_8_8_6_6_6_6_6_6_6_6_6_nan_nan_nan_nan_...,8_8_8_8_8_8_6_6_6_6_6_6_6_6_6_nan_nan_nan_nan_...,100_100_100_100_100_100_100_100_100_100_100_10...,G_G
618453,AL,01_00000000000S702,Not Applicable,Escambia County,'PERDIDO CREEK','11.4KM NW OF ATMORE AL',99.99,1.5,31061094,087341348,3,"Non-Toll Bridge, Non-Toll Road",62,Rural: Local,1999,2,0,50,2019,MS 18,9.7,30,0,"Open, no restriction",1,5,Prestressed concrete,Other,Other,1,0,14.7,15,9.7,9.7,Allowable Stress (AS),NaN,2,32.7,NaN,NaN,0,02-2019,24,NaN,N,NaN,NaN,NaN,NaN,0,0,0,2019,2-way traffic,NaN,0,Concrete Precast Panels,Bituminous,None,Epoxy Coated Reinforcing,1,NaN,59,2039,62,145.5,01,8_8_8_8_8_8_7_7_7_8_8_8_8_8_8_8_8_8_nan_nan_na...,8_8_8_8_8_8_7_7_7_8_8_8_8_8_8_8_8_8_nan_nan_na...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_na...,6_6_8_8_8_8_7_7_7_7_7_7_7_7_7_8_8_8_nan_nan_na...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_nan_nan_na...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_na...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_na...,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_8_8_8_nan_nan_na...,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_8_8_8_nan_nan_na...,8_8_8_8_8_8_6_6_6_6_6_6_6_6_6_6_6_6_nan_nan_na...,100_100_100_100_100_100_100_100_100_100_100_10...,G_G

In [13]:
strut_df = pd.read_csv(revis_path,dtype=str)

In [14]:
strut_df

       STRUCTURE_NUMBER_008                 STRUCTURE_TYPE_STR
0        78_STX8205                                       Slab
1        78_STX8001          Culvert (includes frame culverts)
2        78_STX7520          Culvert (includes frame culverts)
3        78_STX73205             Stringer/Multi-beam or Girder
4        78_STX7310                                       Slab
...                     ...                                ...
618450   01_000001014002450                       Truss - Thru
618451   01_000000883039900     Box Beam or Girders - Multiple
618452   01_0000000000M0022                           Tee Beam
618453   01_00000000000S703                               Slab
618454   01_00000000000S702     Box Beam or Girders - Multiple

[618455 rows x 2 columns]

In [15]:
df_merged = pd.merge(full_df, strut_df, left_on="STRUCTURE_NUMBER_008",right_on='STRUCTURE_NUMBER_008',how='left')

In [16]:
df_merged

,STATE_ABBV,STRUCTURE_NUMBER_008,DIRECTION_005E,COUNTY_CODE_003,FEATURES_DESC_006A,LOCATION_009,MIN_VERT_CLR_010,KILOPOINT_011,LAT_016,LONG_017,DETOUR_KILOS_019,TOLL_020,MAINTENANCE_021,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,TRAFFIC_LANES_ON_028A,TRAFFIC_LANES_UND_028B,ADT_029,YEAR_ADT_030,DESIGN_LOAD_031,APPR_WIDTH_MT_032,DEGREES_SKEW_034,STRUCTURE_FLARED_035,OPEN_CLOSED_POSTED_041,SERVICE_ON_042A,SERVICE_UND_042B,STRUCTURE_KIND_043A,APPR_KIND_044A,APPR_TYPE_044B,MAIN_UNIT_SPANS_045,APPR_SPANS_046,MAX_SPAN_LEN_MT_048,STRUCTURE_LEN_MT_049,ROADWAY_WIDTH_MT_051,DECK_WIDTH_MT_052,OPR_RATING_METH_063,OPERATING_RATING_064,INV_RATING_METH_065,INVENTORY_RATING_066,WORK_PROPOSED_075A,WORK_DONE_BY_075B,IMP_LEN_MT_076,DATE_OF_INSPECT_090,INSPECT_FREQ_MONTHS_091,FRACTURE_092A,UNDWATER_LOOK_SEE_092B,SPEC_INSPECT_092C,FRACTURE_LAST_DATE_093A,UNDWATER_LAST_DATE_093B,SPEC_LAST_DATE_093C,BRIDGE_IMP_COST_094,ROADWAY_IMP_COST_095,TOTAL_IMP_COST_096,YEAR_OF_IMP_097,TRAFFIC_DIRECTION_102,TEMP_STRUCTURE_103,YEAR_RECONSTRUCTED_106,DECK_STRUCTURE_TYPE_107,SURFACE_TYPE_108A,MEMBRANE_TYPE_108B,DECK_PROTECTION_108C,PERCENT_ADT_TRUCK_109,PIER_PROTECTION_111,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,SUBMITTED_BY,DECK_AREA,STATE_CODE_001,DECK_COND_COMBINED,SUPERSTRUCTURE_COND_COMBINED,SUBSTRUCTURE_COND_COMBINED,CHANNEL_COND_COMBINED,CULVERT_COND_COMBINED,STRUCTURAL_EVAL_COMBINED,DECK_GEOMETRY_EVAL_COMBINED,WATERWAY_EVAL_COMBINED,APPR_ROAD_EVAL_COMBINED,SCOUR_CRITICAL_COMBINED,SUFFICIENCY_RATING_COMBINED,BRIDGE_CONDITION_COMBINED,STRUCTURE_TYPE_STR
0,WY,56_NEI,Not Applicable,Park County,'Deaver Canal','3 Miles N.W. of Garland',99.99,0.925,44502750,108413910,8,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,2019,2,0,1,2018,HL 93,9.2,0,0,"Open, no restriction",1,5,Concrete continuous,Other,Other,1,0,6.3,6.3,9.1,9.1,NaN,NaN,F,32.4,NaN,NaN,NaN,01-2020,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Not Applicable,Not Applicable (applies only to structures wit...,Not Applicable (applies only to structures wit...,Not Applicable (applies only to structures wit...,0,NaN,1,2038,56,57.33,56,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,G_nan,Culvert (includes frame culverts)
1,WY,56_NEH,Not Applicable,Goshen County,'Willy Draw','1.7 Mi N.E. of Lingle',99.99,3.574,42092990,104192310,13,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,2019,2,0,276,2017,MS 22.5,6.3,0,0,Posted for load (may include other restriction...,1,5,Steel,Other,Other,1,0,12,12.2,7.3,7.6,Load Factor (LF),NaN,1,48.4,NaN,NaN,NaN,01-2020,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Corrugated Steel,Monolithic Concrete (concurrently placed with ...,None,None,17,NaN,453,2037,56,92.72,56,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,G_nan,Stringer/Multi-beam or Girder
2,WY,56_NDY,Not Applicable,Fremont County,'Wind River','Dubois',99.99,161.163,43313079,109370096,159,"Non-Toll Bridge, Non-Toll Road",04,Urban: Local,2019,2,0,99,2018,Other or Unknown,7.3,0,0,"Open, no restriction",1,5,Steel,Other,Other,4,0,8.8,32.7,5.3,7.3,Load Factor (LF),NaN,1,59.4,NaN,NaN,NaN,06-2019,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Wood or Timber,Wood or Timber,None,None,0,NaN,116,2038,56,238.71,56,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,3_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,F_nan,Stringer/Multi-beam or Girder
3,WY,56_NDU,Not Applicable,Park County,'S Fork Shoshone River','13 Mi. S.W. Of Cody',99.99,7.723,44243142,109160416,13,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,2018,2,0,276,2017,HL 93,9.1,0,0,"Open, no restriction",1,5,Prestressed concrete,Other,Other,3,0,18.6,48.8,8.4,9.1,NaN,NaN,8,35.6,38,Work to be done by owners forces,76.2,02-2019,24,NaN,N,NaN,NaN,NaN,NaN,27,30,59,2013,2-way traffic,NaN,0,Concrete Precast Panels,None (no additional concrete thickness or wear...,None,None,10,NaN,453,2037,56,444.08,56,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,G_nan,Tee Beam
4,WY,56_NDP,Not Applicable,Converse County,'S. Fork of Walker Creek','20 miles NE of Douglas',99.99,1.036,42572981,105062189,0,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,1950,2,0,3,2018,Other or Unknown,7.3,0,0,"Open, no restriction",1,5,Steel,Other,Other,1,0,0,7.2,7.3,7.3,Load Factor (LF),NaN,1,67.3,NaN,NaN,NaN,09-2018,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Corrugated Steel,Gravel,None,None,0,Navigation protection not required,4,2038,56,52.56,56,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,5_5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,N_N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,5_5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,U_U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,F_F,Stringer/Multi-beam or Girder
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613283,AL,01_000001014002450,Not Applicable,Lawrence County,'TENNESSEE RIVER','ON WHEELER DAM',4.52,39.429,34481800,087225400,42,"Non-Toll Bridge, Non-Toll Road",67,Rural: Minor Arterial,1937,2,0,5520,2017,M 18,7.9,0,0,"Open, no restriction",5,5,Steel,Girder and Floorbeam System,Stringer/Multi-beam or Girder,2,143,53.3,1981.2,6.1,7.8,Load Factor (LF),NaN,1,23.9,31,Work to be done by contract,1981.2,06-2019,24,24 Months,N,NaN,00-20619,NaN,NaN,50000,2000,60000,NaN,2-way traffic,NaN,1962,Concrete Cast-in-Place,None (no additional concrete thickness or wear...,None,None,10,Navigation protection not required,9000,2037,67,15453.36,01,5_5_5_6_6_6_6_6_6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_7_...,5_5_5_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_...,5_5_5_5_5_6_6_6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_7_...,2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_...,8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,5_5_5_9_9_9_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,45.9_49.9_49.9_59_59_59_59_59_59_59_59_59_59_5...,F_F,Truss - Thru
613284,AL,01_000000883039900,Not Applicable,Franklin County,'LITTLE BEAR CR. DAM SPW','LITTLE BEAR CR DAM',99.99,0,34270600,087581200,16,"Non-Toll Bridge, Non-Toll Road",67,Rural: Minor Collector,1974,2,0,430,2017,MS 18,11.6,99,0,"Open, no restriction",1,9,Prestressed concrete,Other,Other,5,0,14,65.5,8.7,10.5,Load Factor (LF),NaN,1,26.6,NaN,NaN,NaN,06-2018,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Concrete Cast-in-Place,None (no additional concrete thickness or wear...,None,None,5,NaN,600,2037,67,687.75,01,7_7_7_7_7_7_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,7_7_7_7_7_7_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,7_7_7_7_7_7_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,7_7_7_7_7_7_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_...,6_6_6_6_6_6_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,5_5_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_4_4_4_4_4_...,9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_...,5_5_5_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,90.2_90.2_90.2_90.2_94.8_94.7_94.7_94.7_94.8_9...,G_G,Box Beam or Girders - Multiple
613285,AL,01_0000000000M0022,Not Applicable,Russell County,'UCHEE CREEK','3.4 KM S OF SUNSHINE RD',99.99,0,32174330,-0845837.,18,"Non-Toll Bridge, Non-Toll Road",74,Rural: Local,1942,2,0,375,2017,M 18,10.4,0,0,"Open, no restriction",1,5,Concrete,Other,Other,3,0,18.3,43,7.3,9,Allowable Stress (AS),NaN,2,37.2,38,Work to be done by contract,52.8,10-2019,24,NaN,Y60,NaN,NaN,0-2017 Months,NaN,1,1,2,2019,2-way traffic,NaN,0,Concrete Cast-in-Place,Monolithic Concrete (concurrently placed with ...,None,None,35,NaN,400,2039,74,387,01,5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_7_7_7_7_7_7_7_7_...,5_5_5_5_5_5_5_5_5_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_6_6_6_5_6_6_7_7_7_6_6_6_6_6_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_...,5_5_5_5_5_5_5_5_5_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,5_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_N_N_N_N_N_...,8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_7_7_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_8_8_8_8_8_8_8_8_...,5_5_8_8_8_8_8_8_8_8_8_8_8_8_8_7_7_7_7_7_7_7_7_...,69.5_69.5_69.5_68.5_68.5_68.5_68.5_81.6_81.6_8...,F_F,Tee Beam
613286,AL,01_00000000000S703,Not Applicable,Escambia County,'PERDIDO CREEK','ON LYNN MCGEE ROAD',99.99,1.1,31062020,087340890,3,"Non-Toll Bridge, Non-Toll Road",62,Rural: Local,2002,2,0,159,2019,MS 18,6.5,0,0,"Open, no restriction",1,5,Prestressed concrete,Other,Other,1,0,12.9,13.6,9.1,9.8,Allowable Stress (AS),NaN,2,35.1,NaN,NaN,0,02-2019,24,NaN,N,NaN,NaN,NaN,NaN,0,0,0,2019,2-way traffic,NaN,0,Concrete Precast Panels,Bituminous,None,Unknown,1,NaN,200,2039,62,133.28,01,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,8_8_8_8_8_8_6_6_6_6_6_6_6_6_6_nan_nan_nan_nan_...,8_8_8_8_8_8_6_6_6_6_6_6_6_6_6_nan_nan_nan_nan_...,100_100_100_100_100_100_100_100_100_100_100_10...,G_G,Slab
613287,AL,01_00000000000S702,Not Applicable,Escambia County,'PERDIDO CREEK','11.4KM NW OF ATMORE AL',99.99,1.5,31061094,087341348,3,"Non-Toll Bridge, Non-Toll Road",62,Rural: Local,1999,2,0,50,2019,MS 18,9.7,30,0,"Open, no restriction",1,5,Prestressed concrete,Other,Other,1,0,14.7,15,9.7,9.7,Allowable Stress (AS),NaN,2,32.7,NaN,NaN,0,02-2019,24,NaN,N,NaN,NaN,NaN,NaN,0,0,0,2019,2-way traffic,NaN,0,Concrete Precast Panels,Bituminous,None,Epoxy Coated Reinforcing,1,NaN,59,2039,62,145.5,01,8_8_8_8_8_8_7_7_7_8_8_8_8_8_8_8_8_8_nan_nan_na...,8_8_8_8_8_8_7_7_7_8_8_8_8_8_8_8_8_8_nan_nan_na...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_na...,6_6_8_8_8_8_7_7_7_7_7_7_7_7_7_8_8_8_nan_nan_na...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_nan_nan_na...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_na...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_na...,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_8_8_8_nan_nan_na...,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_8_8_8_nan_nan_na...,8_8_8_8_8_8_6_6_6_6_6_6_6_6_6_6_6_6_nan_nan_na...,100_100_100_100_100_100_100_100_100_100_100_10...,G_G,Box Beam or Girders - Multiple

In [17]:
df_merged.drop('STATE_CODE_001',axis=1,inplace=True)

In [18]:
df_merged.reset_index(drop=True,inplace=True)

In [19]:
df_merged

,STATE_ABBV,STRUCTURE_NUMBER_008,DIRECTION_005E,COUNTY_CODE_003,FEATURES_DESC_006A,LOCATION_009,MIN_VERT_CLR_010,KILOPOINT_011,LAT_016,LONG_017,DETOUR_KILOS_019,TOLL_020,MAINTENANCE_021,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,TRAFFIC_LANES_ON_028A,TRAFFIC_LANES_UND_028B,ADT_029,YEAR_ADT_030,DESIGN_LOAD_031,APPR_WIDTH_MT_032,DEGREES_SKEW_034,STRUCTURE_FLARED_035,OPEN_CLOSED_POSTED_041,SERVICE_ON_042A,SERVICE_UND_042B,STRUCTURE_KIND_043A,APPR_KIND_044A,APPR_TYPE_044B,MAIN_UNIT_SPANS_045,APPR_SPANS_046,MAX_SPAN_LEN_MT_048,STRUCTURE_LEN_MT_049,ROADWAY_WIDTH_MT_051,DECK_WIDTH_MT_052,OPR_RATING_METH_063,OPERATING_RATING_064,INV_RATING_METH_065,INVENTORY_RATING_066,WORK_PROPOSED_075A,WORK_DONE_BY_075B,IMP_LEN_MT_076,DATE_OF_INSPECT_090,INSPECT_FREQ_MONTHS_091,FRACTURE_092A,UNDWATER_LOOK_SEE_092B,SPEC_INSPECT_092C,FRACTURE_LAST_DATE_093A,UNDWATER_LAST_DATE_093B,SPEC_LAST_DATE_093C,BRIDGE_IMP_COST_094,ROADWAY_IMP_COST_095,TOTAL_IMP_COST_096,YEAR_OF_IMP_097,TRAFFIC_DIRECTION_102,TEMP_STRUCTURE_103,YEAR_RECONSTRUCTED_106,DECK_STRUCTURE_TYPE_107,SURFACE_TYPE_108A,MEMBRANE_TYPE_108B,DECK_PROTECTION_108C,PERCENT_ADT_TRUCK_109,PIER_PROTECTION_111,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,SUBMITTED_BY,DECK_AREA,DECK_COND_COMBINED,SUPERSTRUCTURE_COND_COMBINED,SUBSTRUCTURE_COND_COMBINED,CHANNEL_COND_COMBINED,CULVERT_COND_COMBINED,STRUCTURAL_EVAL_COMBINED,DECK_GEOMETRY_EVAL_COMBINED,WATERWAY_EVAL_COMBINED,APPR_ROAD_EVAL_COMBINED,SCOUR_CRITICAL_COMBINED,SUFFICIENCY_RATING_COMBINED,BRIDGE_CONDITION_COMBINED,STRUCTURE_TYPE_STR
0,WY,56_NEI,Not Applicable,Park County,'Deaver Canal','3 Miles N.W. of Garland',99.99,0.925,44502750,108413910,8,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,2019,2,0,1,2018,HL 93,9.2,0,0,"Open, no restriction",1,5,Concrete continuous,Other,Other,1,0,6.3,6.3,9.1,9.1,NaN,NaN,F,32.4,NaN,NaN,NaN,01-2020,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Not Applicable,Not Applicable (applies only to structures wit...,Not Applicable (applies only to structures wit...,Not Applicable (applies only to structures wit...,0,NaN,1,2038,56,57.33,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,G_nan,Culvert (includes frame culverts)
1,WY,56_NEH,Not Applicable,Goshen County,'Willy Draw','1.7 Mi N.E. of Lingle',99.99,3.574,42092990,104192310,13,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,2019,2,0,276,2017,MS 22.5,6.3,0,0,Posted for load (may include other restriction...,1,5,Steel,Other,Other,1,0,12,12.2,7.3,7.6,Load Factor (LF),NaN,1,48.4,NaN,NaN,NaN,01-2020,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Corrugated Steel,Monolithic Concrete (concurrently placed with ...,None,None,17,NaN,453,2037,56,92.72,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,G_nan,Stringer/Multi-beam or Girder
2,WY,56_NDY,Not Applicable,Fremont County,'Wind River','Dubois',99.99,161.163,43313079,109370096,159,"Non-Toll Bridge, Non-Toll Road",04,Urban: Local,2019,2,0,99,2018,Other or Unknown,7.3,0,0,"Open, no restriction",1,5,Steel,Other,Other,4,0,8.8,32.7,5.3,7.3,Load Factor (LF),NaN,1,59.4,NaN,NaN,NaN,06-2019,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Wood or Timber,Wood or Timber,None,None,0,NaN,116,2038,56,238.71,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,3_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,F_nan,Stringer/Multi-beam or Girder
3,WY,56_NDU,Not Applicable,Park County,'S Fork Shoshone River','13 Mi. S.W. Of Cody',99.99,7.723,44243142,109160416,13,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,2018,2,0,276,2017,HL 93,9.1,0,0,"Open, no restriction",1,5,Prestressed concrete,Other,Other,3,0,18.6,48.8,8.4,9.1,NaN,NaN,8,35.6,38,Work to be done by owners forces,76.2,02-2019,24,NaN,N,NaN,NaN,NaN,NaN,27,30,59,2013,2-way traffic,NaN,0,Concrete Precast Panels,None (no additional concrete thickness or wear...,None,None,10,NaN,453,2037,56,444.08,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,G_nan,Tee Beam
4,WY,56_NDP,Not Applicable,Converse County,'S. Fork of Walker Creek','20 miles NE of Douglas',99.99,1.036,42572981,105062189,0,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,1950,2,0,3,2018,Other or Unknown,7.3,0,0,"Open, no restriction",1,5,Steel,Other,Other,1,0,0,7.2,7.3,7.3,Load Factor (LF),NaN,1,67.3,NaN,NaN,NaN,09-2018,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Corrugated Steel,Gravel,None,None,0,Navigation protection not required,4,2038,56,52.56,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,5_5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,N_N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,5_5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,U_U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,F_F,Stringer/Multi-beam or Girder
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613283,AL,01_000001014002450,Not Applicable,Lawrence County,'TENNESSEE RIVER','ON WHEELER DAM',4.52,39.429,34481800,087225400,42,"Non-Toll Bridge, Non-Toll Road",67,Rural: Minor Arterial,1937,2,0,5520,2017,M 18,7.9,0,0,"Open, no restriction",5,5,Steel,Girder and Floorbeam System,Stringer/Multi-beam or Girder,2,143,53.3,1981.2,6.1,7.8,Load Factor (LF),NaN,1,23.9,31,Work to be done by contract,1981.2,06-2019,24,24 Months,N,NaN,00-20619,NaN,NaN,50000,2000,60000,NaN,2-way traffic,NaN,1962,Concrete Cast-in-Place,None (no additional concrete thickness or wear...,None,None,10,Navigation protection not required,9000,2037,67,15453.36,5_5_5_6_6_6_6_6_6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_7_...,5_5_5_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_...,5_5_5_5_5_6_6_6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_7_...,2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_...,8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,5_5_5_9_9_9_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,45.9_49.9_49.9_59_59_59_59_59_59_59_59_59_59_5...,F_F,Truss - Thru
613284,AL,01_000000883039900,Not Applicable,Franklin County,'LITTLE BEAR CR. DAM SPW','LITTLE BEAR CR DAM',99.99,0,34270600,087581200,16,"Non-Toll Bridge, Non-Toll Road",67,Rural: Minor Collector,1974,2,0,430,2017,MS 18,11.6,99,0,"Open, no restriction",1,9,Prestressed concrete,Other,Other,5,0,14,65.5,8.7,10.5,Load Factor (LF),NaN,1,26.6,NaN,NaN,NaN,06-2018,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Concrete Cast-in-Place,None (no additional concrete thickness or wear...,None,None,5,NaN,600,2037,67,687.75,7_7_7_7_7_7_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,7_7_7_7_7_7_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,7_7_7_7_7_7_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,7_7_7_7_7_7_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_...,6_6_6_6_6_6_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,5_5_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_4_4_4_4_4_...,9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_...,5_5_5_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,90.2_90.2_90.2_90.2_94.8_94.7_94.7_94.7_94.8_9...,G_G,Box Beam or Girders - Multiple
613285,AL,01_0000000000M0022,Not Applicable,Russell County,'UCHEE CREEK','3.4 KM S OF SUNSHINE RD',99.99,0,32174330,-0845837.,18,"Non-Toll Bridge, Non-Toll Road",74,Rural: Local,1942,2,0,375,2017,M 18,10.4,0,0,"Open, no restriction",1,5,Concrete,Other,Other,3,0,18.3,43,7.3,9,Allowable Stress (AS),NaN,2,37.2,38,Work to be done by contract,52.8,10-2019,24,NaN,Y60,NaN,NaN,0-2017 Months,NaN,1,1,2,2019,2-way traffic,NaN,0,Concrete Cast-in-Place,Monolithic Concrete (concurrently placed with ...,None,None,35,NaN,400,2039,74,387,5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_7_7_7_7_7_7_7_7_...,5_5_5_5_5_5_5_5_5_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_6_6_6_5_6_6_7_7_7_6_6_6_6_6_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_...,5_5_5_5_5_5_5_5_5_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,5_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_N_N_N_N_N_...,8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_7_7_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_8_8_8_8_8_8_8_8_...,5_5_8_8_8_8_8_8_8_8_8_8_8_8_8_7_7_7_7_7_7_7_7_...,69.5_69.5_69.5_68.5_68.5_68.5_68.5_81.6_81.6_8...,F_F,Tee Beam
613286,AL,01_00000000000S703,Not Applicable,Escambia County,'PERDIDO CREEK','ON LYNN MCGEE ROAD',99.99,1.1,31062020,087340890,3,"Non-Toll Bridge, Non-Toll Road",62,Rural: Local,2002,2,0,159,2019,MS 18,6.5,0,0,"Open, no restriction",1,5,Prestressed concrete,Other,Other,1,0,12.9,13.6,9.1,9.8,Allowable Stress (AS),NaN,2,35.1,NaN,NaN,0,02-2019,24,NaN,N,NaN,NaN,NaN,NaN,0,0,0,2019,2-way traffic,NaN,0,Concrete Precast Panels,Bituminous,None,Unknown,1,NaN,200,2039,62,133.28,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,8_8_8_8_8_8_6_6_6_6_6_6_6_6_6_nan_nan_nan_nan_...,8_8_8_8_8_8_6_6_6_6_6_6_6_6_6_nan_nan_nan_nan_...,100_100_100_100_100_100_100_100_100_100_100_10...,G_G,Slab
613287,AL,01_00000000000S702,Not Applicable,Escambia County,'PERDIDO CREEK','11.4KM NW OF ATMORE AL',99.99,1.5,31061094,087341348,3,"Non-Toll Bridge, Non-Toll Road",62,Rural: Local,1999,2,0,50,2019,MS 18,9.7,30,0,"Open, no restriction",1,5,Prestressed concrete,Other,Other,1,0,14.7,15,9.7,9.7,Allowable Stress (AS),NaN,2,32.7,NaN,NaN,0,02-2019,24,NaN,N,NaN,NaN,NaN,NaN,0,0,0,2019,2-way traffic,NaN,0,Concrete Precast Panels,Bituminous,None,Epoxy Coated Reinforcing,1,NaN,59,2039,62,145.5,8_8_8_8_8_8_7_7_7_8_8_8_8_8_8_8_8_8_nan_nan_na...,8_8_8_8_8_8_7_7_7_8_8_8_8_8_8_8_8_8_nan_nan_na...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_na...,6_6_8_8_8_8_7_7_7_7_7_7_7_7_7_8_8_8_nan_nan_na...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_nan_nan_na...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_na...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_na...,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_8_8_8_nan_nan_na...,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_8_8_8_nan_nan_na...,8_8_8_8_8_8_6_6_6_6_6_6_6_6_6_6_6_6_nan_nan_na...,100_100_100_100_100_100_100_100_100_100_100_10...,G_G,Box Beam or Girders - Multiple

In [20]:
def long_cleaning_function(x):
    magnitudes = np.array([1,10,100,1000,10000,100000,1000000,10000000,100000000,1000000000])
    if abs(x/1e6)>66.55 and abs(x/1e6)<124.26:
        x_new =  -(int(abs(x)/1e6) + int(abs(x)%1e6/1e4)/60 + abs(x)%1e4/36e4)
    else:
        x_new = x
    
    if x_new > 0.00001:
        x_new = -x_new
    
    
    diff1 = (-125.0 - x_new)
    div_out = diff1/magnitudes
    div_out1 = np.where(div_out<125.0,1,0)
    div_out2 = np.where(div_out>65.0,1,0)
    div_order_idx = np.argmax(div_out1+div_out2)
    mag_i = magnitudes[div_order_idx]
    x_new = x_new/mag_i
    return x_new

In [21]:
#def lat_cleaning_function(x):
#    if abs(x/1e6)>24.21 and abs(x/1e6)<49:
#        return int(abs(x)/1e6) + int(abs(x)%1e6/1e4)/60 + abs(x)%1e4/36e4
#    else:
#        return x

def lat_cleaning_function(x):
    
    if abs(x/1e6)>24.21 and abs(x/1e6)<49:
        x_new = int(abs(x)/1e6) + int(abs(x)%1e6/1e4)/60 + abs(x)%1e4/36e4
    else:
        x_new = x
    if x_new < 0.00000:
        x_new = -x_new

    magnitudes = np.array([1,10,100,1000,10000,100000,1000000,10000000,100000000,1000000000])

    diff1 = (x_new-60.0)
    div_out = diff1/magnitudes
    div_out1 = np.where(div_out<60.0,1,0)
    div_out2 = np.where(div_out>20.0,1,0)
    div_order_idx = np.argmax(div_out1+div_out2)
    mag_i = magnitudes[div_order_idx]
    x_new = x_new/mag_i

    return x_new

In [22]:
df_merged['LONG_New'] = df_merged.apply(lambda x: long_cleaning_function(float(x['LONG_017'])),axis=1)
df_merged['LAT_New'] = df_merged.apply(lambda x: lat_cleaning_function(float(x['LAT_016'])),axis=1)

df_merged = df_merged[df_merged['LAT_New'] != 0.0]
df_merged = df_merged[df_merged['LAT_New'] >= 20.0]
df_merged = df_merged[df_merged['LAT_New'] <= 60.0]
df_merged = df_merged[df_merged['LONG_New'] <= 0.0]
df_merged = df_merged[df_merged['LONG_New'] <= -60.0]
df_merged = df_merged[df_merged['LONG_New'] >= -130.0]

In [23]:
df_merged.drop(columns=['LAT_016','LONG_017'],inplace=True)
df_merged = df_merged.rename(columns={'LONG_New': 'LONG_017', 'LAT_New': 'LAT_016'})

In [24]:
df_merged

,STATE_ABBV,STRUCTURE_NUMBER_008,DIRECTION_005E,COUNTY_CODE_003,FEATURES_DESC_006A,LOCATION_009,MIN_VERT_CLR_010,KILOPOINT_011,DETOUR_KILOS_019,TOLL_020,MAINTENANCE_021,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,TRAFFIC_LANES_ON_028A,TRAFFIC_LANES_UND_028B,ADT_029,YEAR_ADT_030,DESIGN_LOAD_031,APPR_WIDTH_MT_032,DEGREES_SKEW_034,STRUCTURE_FLARED_035,OPEN_CLOSED_POSTED_041,SERVICE_ON_042A,SERVICE_UND_042B,STRUCTURE_KIND_043A,APPR_KIND_044A,APPR_TYPE_044B,MAIN_UNIT_SPANS_045,APPR_SPANS_046,MAX_SPAN_LEN_MT_048,STRUCTURE_LEN_MT_049,ROADWAY_WIDTH_MT_051,DECK_WIDTH_MT_052,OPR_RATING_METH_063,OPERATING_RATING_064,INV_RATING_METH_065,INVENTORY_RATING_066,WORK_PROPOSED_075A,WORK_DONE_BY_075B,IMP_LEN_MT_076,DATE_OF_INSPECT_090,INSPECT_FREQ_MONTHS_091,FRACTURE_092A,UNDWATER_LOOK_SEE_092B,SPEC_INSPECT_092C,FRACTURE_LAST_DATE_093A,UNDWATER_LAST_DATE_093B,SPEC_LAST_DATE_093C,BRIDGE_IMP_COST_094,ROADWAY_IMP_COST_095,TOTAL_IMP_COST_096,YEAR_OF_IMP_097,TRAFFIC_DIRECTION_102,TEMP_STRUCTURE_103,YEAR_RECONSTRUCTED_106,DECK_STRUCTURE_TYPE_107,SURFACE_TYPE_108A,MEMBRANE_TYPE_108B,DECK_PROTECTION_108C,PERCENT_ADT_TRUCK_109,PIER_PROTECTION_111,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,SUBMITTED_BY,DECK_AREA,DECK_COND_COMBINED,SUPERSTRUCTURE_COND_COMBINED,SUBSTRUCTURE_COND_COMBINED,CHANNEL_COND_COMBINED,CULVERT_COND_COMBINED,STRUCTURAL_EVAL_COMBINED,DECK_GEOMETRY_EVAL_COMBINED,WATERWAY_EVAL_COMBINED,APPR_ROAD_EVAL_COMBINED,SCOUR_CRITICAL_COMBINED,SUFFICIENCY_RATING_COMBINED,BRIDGE_CONDITION_COMBINED,STRUCTURE_TYPE_STR,LONG_017,LAT_016
0,WY,56_NEI,Not Applicable,Park County,'Deaver Canal','3 Miles N.W. of Garland',99.99,0.925,8,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,2019,2,0,1,2018,HL 93,9.2,0,0,"Open, no restriction",1,5,Concrete continuous,Other,Other,1,0,6.3,6.3,9.1,9.1,NaN,NaN,F,32.4,NaN,NaN,NaN,01-2020,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Not Applicable,Not Applicable (applies only to structures wit...,Not Applicable (applies only to structures wit...,Not Applicable (applies only to structures wit...,0,NaN,1,2038,56,57.33,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,G_nan,Culvert (includes frame culverts),-108.694194,44.840972
1,WY,56_NEH,Not Applicable,Goshen County,'Willy Draw','1.7 Mi N.E. of Lingle',99.99,3.574,13,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,2019,2,0,276,2017,MS 22.5,6.3,0,0,Posted for load (may include other restriction...,1,5,Steel,Other,Other,1,0,12,12.2,7.3,7.6,Load Factor (LF),NaN,1,48.4,NaN,NaN,NaN,01-2020,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Corrugated Steel,Monolithic Concrete (concurrently placed with ...,None,None,17,NaN,453,2037,56,92.72,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,G_nan,Stringer/Multi-beam or Girder,-104.323083,42.158306
2,WY,56_NDY,Not Applicable,Fremont County,'Wind River','Dubois',99.99,161.163,159,"Non-Toll Bridge, Non-Toll Road",04,Urban: Local,2019,2,0,99,2018,Other or Unknown,7.3,0,0,"Open, no restriction",1,5,Steel,Other,Other,4,0,8.8,32.7,5.3,7.3,Load Factor (LF),NaN,1,59.4,NaN,NaN,NaN,06-2019,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Wood or Timber,Wood or Timber,None,None,0,NaN,116,2038,56,238.71,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,3_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,F_nan,Stringer/Multi-beam or Girder,-109.616933,43.525219
3,WY,56_NDU,Not Applicable,Park County,'S Fork Shoshone River','13 Mi. S.W. Of Cody',99.99,7.723,13,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,2018,2,0,276,2017,HL 93,9.1,0,0,"Open, no restriction",1,5,Prestressed concrete,Other,Other,3,0,18.6,48.8,8.4,9.1,NaN,NaN,8,35.6,38,Work to be done by owners forces,76.2,02-2019,24,NaN,N,NaN,NaN,NaN,NaN,27,30,59,2013,2-way traffic,NaN,0,Concrete Precast Panels,None (no additional concrete thickness or wear...,None,None,10,NaN,453,2037,56,444.08,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,G_nan,Tee Beam,-109.267822,44.408728
4,WY,56_NDP,Not Applicable,Converse County,'S. Fork of Walker Creek','20 miles NE of Douglas',99.99,1.036,0,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,1950,2,0,3,2018,Other or Unknown,7.3,0,0,"Open, no restriction",1,5,Steel,Other,Other,1,0,0,7.2,7.3,7.3,Load Factor (LF),NaN,1,67.3,NaN,NaN,NaN,09-2018,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Corrugated Steel,Gravel,None,None,0,Navigation protection not required,4,2038,56,52.56,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,5_5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,N_N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,5_5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,U_U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,F_F,Stringer/Multi-beam or Girder,-105.106081,42.958281
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613283,AL,01_000001014002450,Not Applicable,Lawrence County,'TENNESSEE RIVER','ON WHEELER DAM',4.52,39.429,42,"Non-Toll Bridge, Non-Toll Road",67,Rural: Minor Arterial,1937,2,0,5520,2017,M 18,7.9,0,0,"Open, no restriction",5,5,Steel,Girder and Floorbeam System,Stringer/Multi-beam or Girder,2,143,53.3,1981.2,6.1,7.8,Load Factor (LF),NaN,1,23.9,31,Work to be done by contract,1981.2,06-2019,24,24 Months,N,NaN,00-20619,NaN,NaN,50000,2000,60000,NaN,2-way traffic,NaN,1962,Concrete Cast-in-Place,None (no additional concrete thickness or wear...,None,None,10,Navigation protection not required,9000,2037,67,15453.36,5_5_5_6_6_6_6_6_6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_7_...,5_5_5_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_...,5_5_5_5_5_6_6_6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_7_...,2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_...,8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,5_5_5_9_9_9_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,45.9_49.9_49.9_59_59_59_59_59_59_59_59_59_59_5...,F_F,Truss - Thru,-87.381667,34.805000
613284,AL,01_000000883039900,Not Applicable,Franklin County,'LITTLE BEAR CR. DAM SPW','LITTLE BEAR CR DAM',99.99,0,16,"Non-Toll Bridge, Non-Toll Road",67,Rural: Minor Collector,1974,2,0,430,2017,MS 18,11.6,99,0,"Open, no restriction",1,9,Prestressed concrete,Other,Other,5,0,14,65.5,8.7,10.5,Load Factor (LF),NaN,1,26.6,NaN,NaN,NaN,06-2018,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Concrete Cast-in-Place,None (no additional concrete thickness or wear...,None,None,5,NaN,600,2037,67,687.75,7_7_7_7_7_7_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,7_7_7_7_7_7_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,7_7_7_7_7_7_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,7_7_7_7_7_7_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_...,6_6_6_6_6_6_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,5_5_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_4_4_4_4_4_...,9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_...,5_5_5_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,90.2_90.2_90.2_90.2_94.8_94.7_94.7_94.7_94.8_9...,G_G,Box Beam or Girders - Multiple,-87.970000,34.451667
613285,AL,01_0000000000M0022,Not Applicable,Russell County,'UCHEE CREEK','3.4 KM S OF SUNSHINE RD',99.99,0,18,"Non-Toll Bridge, Non-Toll Road",74,Rural: Local,1942,2,0,375,2017,M 18,10.4,0,0,"Open, no restriction",1,5,Concrete,Other,Other,3,0,18.3,43,7.3,9,Allowable Stress (AS),NaN,2,37.2,38,Work to be done by contract,52.8,10-2019,24,NaN,Y60,NaN,NaN,0-2017 Months,NaN,1,1,2,2019,2-way traffic,NaN,0,Concrete Cast-in-Place,Monolithic Concrete (concurrently placed with ...,None,None,35,NaN,400,2039,74,387,5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_7_7_7_7_7_7_7_7_...,5_5_5_5_5_5_5_5_5_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_6_6_6_5_6_6_7_7_7_6_6_6_6_6_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_...,5_5_5_5_5_5_5_5_5_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,5_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_N_N_N_N_N_...,8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_7_7_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_8_8_8_8_8_8_8_8_...,5_5_8_8_8_8_8_8_8_8_8_8_8_8_8_7_7_7_7_7_7_7_7_...,69.5_69.5_69.5_68.5_68.5_68.5_68.5_81.6_81.6_8...,F_F,Tee Beam,-84.583700,32.295361
613286,AL,01_00000000000S703,Not Applicable,Escambia County,'PERDIDO CREEK','ON LYNN MCGEE ROAD',99.99,1.1,3,"Non-Toll Bridge, Non-Toll Road",62,Rural: Local,2002,2,0,159,2019,MS 18,6.5,0,0,"Open, no restriction",1,5,Prestressed concrete,Other,Other,1,0,12.9,13.6,9.1,9.8,Allowable Stress (AS),NaN,2,35.1,NaN,NaN,0,02-2019,24,NaN,N,NaN,NaN,NaN,NaN,0,0,0,2019,2-way traffic,NaN,0,Concrete Precast Panels,Bituminous,None,Unknown,1,NaN,200,2039,62,133.28,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,8_8_8_8_8_8_6_6_6_6_6_6_6_6_6_nan_nan_nan_nan_...,8_8_8_8_8_8_6_6_6_6_6_6_6_6_6_nan_nan_nan_nan_...,100_100_100_100_100_100_100_100_100_100_100_10...,G_G,Slab,-87.569139,31.105611
613287,AL,01_00000000000S702,Not Applicable,Escambia County,'PERDIDO CREEK','11.4KM NW OF ATMORE AL',99.99,1.5,3,"Non-Toll Bridge, Non-Toll Road",62,Rural: Local,1999,2,0,50,2019,MS 18,9.7,30,0,"Open, no restriction",1,5,Prestressed concrete,Other,Other,1,0,14.7,15,9.7,9.7,Allowable Stress (AS),NaN,2,32.7,NaN,NaN,0,02-2019,24,NaN,N,NaN,NaN,NaN,NaN,0,0,0,2019,2-way traffic,NaN,0,Concrete Precast Panels,Bituminous,None,Epoxy Coated Reinforcing,1,NaN,59,2039,62,145.5,8_8_8_8_8_8_7_7_7_8_8_8_8_8_8_8_8_8_nan_nan_na...,8_8_8_8_8_8_7_7_7_8_8_8_8_8_8_8_8_8_nan_nan_na...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_na...,6_6_8_8_8_8_7_7_7_7_7_7_7_7_7_8_8_8_nan_nan_na...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_nan_nan_na...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_na...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_na...,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_8_8_8_nan_nan_na...,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_8_8_8_nan_nan_na...,8_8_8_8_8_8_6_6_6_6_6_6_6_6_6_6_6_6_nan_nan_na...,100_100_100_100_100_100_100_100_100_100_100_10...,G_G,Box Beam or Girders - Multiple,-87.570411,31.103039

In [25]:
df_merged['STRUCTURE_NUMBER_008'] = df_merged.apply(lambda x: x['STRUCTURE_NUMBER_008'].rstrip(),axis=1)

In [26]:
exclude_list = pd.read_csv('D:\\Bridge_Data\\CSV\\Exclude_List.csv')
exclude_ids = np.array(exclude_list['Structure Number 008'])
for i in range(0,exclude_ids.shape[0]):
    df_merged = df_merged[df_merged['STRUCTURE_NUMBER_008'] != exclude_ids[i]]

In [27]:
df_merged

,STATE_ABBV,STRUCTURE_NUMBER_008,DIRECTION_005E,COUNTY_CODE_003,FEATURES_DESC_006A,LOCATION_009,MIN_VERT_CLR_010,KILOPOINT_011,DETOUR_KILOS_019,TOLL_020,MAINTENANCE_021,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,TRAFFIC_LANES_ON_028A,TRAFFIC_LANES_UND_028B,ADT_029,YEAR_ADT_030,DESIGN_LOAD_031,APPR_WIDTH_MT_032,DEGREES_SKEW_034,STRUCTURE_FLARED_035,OPEN_CLOSED_POSTED_041,SERVICE_ON_042A,SERVICE_UND_042B,STRUCTURE_KIND_043A,APPR_KIND_044A,APPR_TYPE_044B,MAIN_UNIT_SPANS_045,APPR_SPANS_046,MAX_SPAN_LEN_MT_048,STRUCTURE_LEN_MT_049,ROADWAY_WIDTH_MT_051,DECK_WIDTH_MT_052,OPR_RATING_METH_063,OPERATING_RATING_064,INV_RATING_METH_065,INVENTORY_RATING_066,WORK_PROPOSED_075A,WORK_DONE_BY_075B,IMP_LEN_MT_076,DATE_OF_INSPECT_090,INSPECT_FREQ_MONTHS_091,FRACTURE_092A,UNDWATER_LOOK_SEE_092B,SPEC_INSPECT_092C,FRACTURE_LAST_DATE_093A,UNDWATER_LAST_DATE_093B,SPEC_LAST_DATE_093C,BRIDGE_IMP_COST_094,ROADWAY_IMP_COST_095,TOTAL_IMP_COST_096,YEAR_OF_IMP_097,TRAFFIC_DIRECTION_102,TEMP_STRUCTURE_103,YEAR_RECONSTRUCTED_106,DECK_STRUCTURE_TYPE_107,SURFACE_TYPE_108A,MEMBRANE_TYPE_108B,DECK_PROTECTION_108C,PERCENT_ADT_TRUCK_109,PIER_PROTECTION_111,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,SUBMITTED_BY,DECK_AREA,DECK_COND_COMBINED,SUPERSTRUCTURE_COND_COMBINED,SUBSTRUCTURE_COND_COMBINED,CHANNEL_COND_COMBINED,CULVERT_COND_COMBINED,STRUCTURAL_EVAL_COMBINED,DECK_GEOMETRY_EVAL_COMBINED,WATERWAY_EVAL_COMBINED,APPR_ROAD_EVAL_COMBINED,SCOUR_CRITICAL_COMBINED,SUFFICIENCY_RATING_COMBINED,BRIDGE_CONDITION_COMBINED,STRUCTURE_TYPE_STR,LONG_017,LAT_016
0,WY,56_NEI,Not Applicable,Park County,'Deaver Canal','3 Miles N.W. of Garland',99.99,0.925,8,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,2019,2,0,1,2018,HL 93,9.2,0,0,"Open, no restriction",1,5,Concrete continuous,Other,Other,1,0,6.3,6.3,9.1,9.1,NaN,NaN,F,32.4,NaN,NaN,NaN,01-2020,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Not Applicable,Not Applicable (applies only to structures wit...,Not Applicable (applies only to structures wit...,Not Applicable (applies only to structures wit...,0,NaN,1,2038,56,57.33,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,G_nan,Culvert (includes frame culverts),-108.694194,44.840972
1,WY,56_NEH,Not Applicable,Goshen County,'Willy Draw','1.7 Mi N.E. of Lingle',99.99,3.574,13,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,2019,2,0,276,2017,MS 22.5,6.3,0,0,Posted for load (may include other restriction...,1,5,Steel,Other,Other,1,0,12,12.2,7.3,7.6,Load Factor (LF),NaN,1,48.4,NaN,NaN,NaN,01-2020,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Corrugated Steel,Monolithic Concrete (concurrently placed with ...,None,None,17,NaN,453,2037,56,92.72,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,G_nan,Stringer/Multi-beam or Girder,-104.323083,42.158306
2,WY,56_NDY,Not Applicable,Fremont County,'Wind River','Dubois',99.99,161.163,159,"Non-Toll Bridge, Non-Toll Road",04,Urban: Local,2019,2,0,99,2018,Other or Unknown,7.3,0,0,"Open, no restriction",1,5,Steel,Other,Other,4,0,8.8,32.7,5.3,7.3,Load Factor (LF),NaN,1,59.4,NaN,NaN,NaN,06-2019,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Wood or Timber,Wood or Timber,None,None,0,NaN,116,2038,56,238.71,7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,3_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,F_nan,Stringer/Multi-beam or Girder,-109.616933,43.525219
3,WY,56_NDU,Not Applicable,Park County,'S Fork Shoshone River','13 Mi. S.W. Of Cody',99.99,7.723,13,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,2018,2,0,276,2017,HL 93,9.1,0,0,"Open, no restriction",1,5,Prestressed concrete,Other,Other,3,0,18.6,48.8,8.4,9.1,NaN,NaN,8,35.6,38,Work to be done by owners forces,76.2,02-2019,24,NaN,N,NaN,NaN,NaN,NaN,27,30,59,2013,2-way traffic,NaN,0,Concrete Precast Panels,None (no additional concrete thickness or wear...,None,None,10,NaN,453,2037,56,444.08,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,8_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,G_nan,Tee Beam,-109.267822,44.408728
4,WY,56_NDP,Not Applicable,Converse County,'S. Fork of Walker Creek','20 miles NE of Douglas',99.99,1.036,0,"Non-Toll Bridge, Non-Toll Road",02,Rural: Local,1950,2,0,3,2018,Other or Unknown,7.3,0,0,"Open, no restriction",1,5,Steel,Other,Other,1,0,0,7.2,7.3,7.3,Load Factor (LF),NaN,1,67.3,NaN,NaN,NaN,09-2018,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Corrugated Steel,Gravel,None,None,0,Navigation protection not required,4,2038,56,52.56,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_6_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,5_5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,N_N_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,5_5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,6_5_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,7_7_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,U_U_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_nan_na...,F_F,Stringer/Multi-beam or Girder,-105.106081,42.958281
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613282,AL,01_000001331700710,Not Applicable,Colbert County,'TENNESSEE RIVER','ON WILSON DAM',99.99,0,6,"Non-Toll Bridge, Non-Toll Road",67,Urban: Collector,1924,2,2,3620,2018,MS 13.5,7.9,0,0,"Open, no restriction",5,6,Steel continuous,Slab,Mixed types,8,78,46.9,1512.4,6.1,8.3,Load Factor (LF),NaN,1,35,31,Work to be done by contract,1512.4,06-2018,24,24 Months,N,NaN,00-20618,NaN,NaN,35000,2000,45000,NaN,2-way traffic,NaN,1958,Concrete Cast-in-Place,Epoxy Overlay,None,None,8,Navigation protection not required,2500,2038,67,12552.92,5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_...,5_5_5_5_5_5_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_...,5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_8_8_8_8_8_8_...,8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_...,5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_5_6_6_6_6_6_6_...,2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_...,9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_...,3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_...,5_5_5_9_9_9_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,61.3_61.3_61.3_55.6_55.6_55.6_55.6_55.6_54_54_...,F_F,Girder and Floorbeam System,-87.625000,34.800000
613283,AL,01_000001014002450,Not Applicable,Lawrence County,'TENNESSEE RIVER','ON WHEELER DAM',4.52,39.429,42,"Non-Toll Bridge, Non-Toll Road",67,Rural: Minor Arterial,1937,2,0,5520,2017,M 18,7.9,0,0,"Open, no restriction",5,5,Steel,Girder and Floorbeam System,Stringer/Multi-beam or Girder,2,143,53.3,1981.2,6.1,7.8,Load Factor (LF),NaN,1,23.9,31,Work to be done by contract,1981.2,06-2019,24,24 Months,N,NaN,00-20619,NaN,NaN,50000,2000,60000,NaN,2-way traffic,NaN,1962,Concrete Cast-in-Place,None (no additional concrete thickness or wear...,None,None,10,Navigation protection not required,9000,2037,67,15453.36,5_5_5_6_6_6_6_6_6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_7_...,5_5_5_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_...,9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_...,5_5_5_5_5_6_6_6_6_6_6_6_6_6_6_6_7_7_7_7_7_7_7_...,2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_...,8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,5_5_5_9_9_9_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,45.9_49.9_49.9_59_59_59_59_59_59_59_59_59_59_5...,F_F,Truss - Thru,-87.381667,34.805000
613284,AL,01_000000883039900,Not Applicable,Franklin County,'LITTLE BEAR CR. DAM SPW','LITTLE BEAR CR DAM',99.99,0,16,"Non-Toll Bridge, Non-Toll Road",67,Rural: Minor Collector,1974,2,0,430,2017,MS 18,11.6,99,0,"Open, no restriction",1,9,Prestressed concrete,Other,Other,5,0,14,65.5,8.7,10.5,Load Factor (LF),NaN,1,26.6,NaN,NaN,NaN,06-2018,24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-way traffic,NaN,0,Concrete Cast-in-Place,None (no additional concrete thickness or wear...,None,None,5,NaN,600,2037,67,687.75,7_7_7_7_7_7_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,7_7_7_7_7_7_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,7_7_7_7_7_7_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,7_7_7_7_7_7_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_...,6_6_6_6_6_6_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,5_5_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_4_4_4_4_4_...,9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_9_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_...,5_5_5_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_8_...,90.2_90.2_90.2_90.2_94.8_94.7_94.7_94.7_94.8_9...,G_G,Box Beam or Girders - Multiple,-87.970000,34.451667
613286,AL,01_00000000000S703,Not Applicable,Escambia County,'PERDIDO CREEK','ON LYNN MCGEE ROAD',99.99,1.1,3,"Non-Toll Bridge, Non-Toll Road",62,Rural: Local,2002,2,0,159,2019,MS 18,6.5,0,0,"Open, no restriction",1,5,Prestressed concrete,Other,Other,1,0,12.9,13.6,9.1,9.8,Allowable Stress (AS),NaN,2,35.1,NaN,NaN,0,02-2019,24,NaN,N,NaN,NaN,NaN,NaN,0,0,0,2019,2-way traffic,NaN,0,Concrete Precast Panels,Bituminous,None,Unknown,1,NaN,200,2039,62,133.28,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_nan_nan_nan_nan_...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_nan_nan_...,8_8_8_8_8_8_6_6_6_6_6_6_6_6_6_nan_nan_nan_nan_...,8_8_8_8_8_8_6_6_6_6_6_6_6_6_6_nan_nan_nan_nan_...,100_100_100_100_100_100_100_100_100_100_100_10...,G_G,Slab,-87.569139,31.105611
613287,AL,01_00000000000S702,Not Applicable,Escambia County,'PERDIDO CREEK','11.4KM NW OF ATMORE AL',99.99,1.5,3,"Non-Toll Bridge, Non-Toll Road",62,Rural: Local,1999,2,0,50,2019,MS 18,9.7,30,0,"Open, no restriction",1,5,Prestressed concrete,Other,Other,1,0,14.7,15,9.7,9.7,Allowable Stress (AS),NaN,2,32.7,NaN,NaN,0,02-2019,24,NaN,N,NaN,NaN,NaN,NaN,0,0,0,2019,2-way traffic,NaN,0,Concrete Precast Panels,Bituminous,None,Epoxy Coated Reinforcing,1,NaN,59,2039,62,145.5,8_8_8_8_8_8_7_7_7_8_8_8_8_8_8_8_8_8_nan_nan_na...,8_8_8_8_8_8_7_7_7_8_8_8_8_8_8_8_8_8_nan_nan_na...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_na...,6_6_8_8_8_8_7_7_7_7_7_7_7_7_7_8_8_8_nan_nan_na...,N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_N_nan_nan_na...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_na...,7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_7_nan_nan_na...,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_8_8_8_nan_nan_na...,8_8_8_8_8_8_7_7_7_7_7_7_7_7_7_8_8_8_nan_nan_na...,8_8_8_8_8_8_6_6_6_6_6_6_6_6_6_6_6_6_nan_nan_na...,100_100_100_100_100_100_100_100_100_100_100_10...,G_G,Box Beam or Girders - Multiple,-87.570411,31.103039

In [28]:
df_merged.to_csv('Cleaned_Full_Data_V6.csv', index=False)